MS-3 Úložiště zdrojových 3D modelů
MetacityTools/Studio pull request #52
Opened 2024-06-14 08:34 UTC by AdamPospisil

https://stdio.youtrack.cloud/issue/MS-3/Uloziste-zdrojovych-3D-modelu

2024-06-14 11:10 UTC, vojtatom requested changes
- přidat klik na drag and drop areu, která otevře file select dialog
- upravit layout formuláře - nejprve drag and drop, pak seznam souborů
- na upload přidat indikátor že se soubor odesílá/je na to tam ta `isLoading` flag
- kouknout na ošetření situace kdy je prázdné jméno souboru prázdné, nebo nejsou vybrány žádné soubory

2024-06-19 09:13 UTC, SmallhillCZ requested changes
.

2024-06-19 09:14 UTC, SmallhillCZ reviewed
Jen dvě poznámky, ale nejsou v zadání tasku tak asi v pohodě.

* nedaří se mi stáhnout nahraný model (není to v user story, ale je tam na to tlačítko)
* nikde není seznam nahraných souborů nebo velikost nebo něco (nebylo to uv user story tak asi nějaký další task)

2024-06-20 11:55 UTC, vojtatom approved these changes

2024-06-20 11:56 UTC, SmallhillCZ approved these changes

2024-06-20 11:56 UTC, merged